const router = require("express").Router()
const userController = require("../controllers/UserController")
const testmiddleware = require("../middlewares/testMiddleware")
const zodmiddleware = require("../middlewares/Zodmiddleware")
const uservalidationschema = require("../validationSchemas/UserValidationSchemas")
const upload = require("../middlewares/UploadMiddleware")

router.get("/users",userController.getAllUsers)
router.get("/user/:id",userController.getUserById)
router.get("/search/:id",userController.searchByid)
router.get("/search2",userController.searchUser2)

// router.post("/user",testmiddleware("admin"),userController.createuser)
// router.post("/user",zodmiddleware(uservalidationschema),userController.createuser)
router.post("/user",upload.array("file",6),userController.createuser)
router.delete("/user/:id",userController.deleteUser)
router.put("/user/:id",userController.updateuser)
router.put("/userbyage/:age",userController.updatebyage)
router.put("/updateuurl",userController.updateusingid)
router.post("/multiuser",upload.single("file"),userController.createMultipuleusers)
router.post("/LoginUser",userController.LoginUser)
module.exports = router